### ISSUE TITLE
JOSS review issue 3 (Installation)

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/WODEN#16]
Export a user-specific version of `init_woden.sh` that includes a custom LD_LIBRARY_PATH for systems with non-standard installations. Warn the user in the Documentation that `init_woden.sh` is overwritten in the `build` directory every time. I think this can be achieved by searching `CMakeCache.txt` and checking for any non-standard paths.

https://github.com/openjournals/joss-reviews/issues/3676

**Comment by JLBLine** [comment]
@plaplant @mkolopanis With commit 74f71f95b34df3b91dcd853f72c49492f2e5920b, I've added new code that generates `init_WODEN.sh` with lines that append the locations of the `erfa`, `pal`, `json`, and `hdf5` libraries to the `LD_LIBRARY_PATH`. This means `woden` should be able to find them at run time. Added a note to the documentation that this is overwritten everytime `make` is run

**Comment by mkolopanis** [comment]
This looks good to me. Thanks for the update.

**Comment by plaplant** [comment]
Thanks for addressing this, looks good to me too.

**Comment by JLBLine** [comment]
Thanks all, I'll close this now.
