### ISSUE TITLE
JOSS review issue 4 (Tests)

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/WODEN#17]
Detail what the unit / integration tests are actually doing in the Documentation, as a standalone section inside `Testing via ctest`. Add plenty of comments and explanations inside the tests themselves as well.

https://github.com/openjournals/joss-reviews/issues/3676

**Comment by JLBLine** [comment]
As of commit aae18882033bb570be006fbdfa2570d929396353 I have a Section called [What do the tests actually do?](https://woden.readthedocs.io/en/joss_review/testing/cmake_testing.html#what-do-the-tests-actually-do), which contains subsection links that detail all the unit tests made for each `src` file.

https://github.com/openjournals/joss-reviews/issues/3676 @mkolopanis @plaplant I think this is enough to address this issue

**Comment by mkolopanis** [comment]
This looks good to me now. thanks for adding this section.

**Comment by plaplant** [comment]
Great update, thanks for the additional info.

**Comment by JLBLine** [comment]
Thanks all, I'll close this now.
