### ISSUE TITLE
JOSS review issue 5 (Code coverage)

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/WODEN#18]
Investigate the use of CMake-codecov to get test coverage of the python/C code

https://github.com/openjournals/joss-reviews/issues/3676

**Comment by JLBLine** [comment]
Ok, with this commit https://github.com/JLBLine/WODEN/commit/620bd121862deca2468659a27b8476756ec13ddc, I've added a way to locally generate code coverage, that can be pushed to "codecov" using a specific token. It relies on running the local CMake tests to generate the coverage outputs. I plan on putting instructions on how obtain this token in the "Community Guidelines". I've written a README in the new directory `coverage_outputs` on how to generate the coverage reports and send them off to "codecov".

To fully automate everything upon pushing, I'd have to separate out all CUDA calls from the CMake setup and have a some kind of way of switching off CUDA entirely from CMake for the code coverage generation. Might be possible but will take quite some time to develop methinks. At least this way, I can give this token to anyone trusted enough to be a contributor, and they can update the "codecov" coverage report themselves before pushing changes.

**Comment by JLBLine** [comment]
Ah oops to run the `ctest` code now you'll need to follow the instructions I've added in commit c29d7eeaf608cdd9da9381289e779d854b752458 to the "Testing via `ctest`" documentation section about initiating a `git submodule`. Otherwise the CMake code can't find what it needs when you run `cmake .. -DTARGET_GROUP=test`

**Comment by mkolopanis** [comment]
Thanks for adding the coverage where you can. I have verified that following the updated documentation produces the desired effects.

**Comment by plaplant** [comment]
Looks great! Thanks for improving the code coverage and adding a way to track it.

**Comment by JLBLine** [comment]
Thanks all, I'll close this now.
