### ISSUE TITLE
JOSS review issue 6 (uvfits files)

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/WODEN#19]
Make the uvfits files work with pyuvdata

https://github.com/openjournals/joss-reviews/issues/3676

**Comment by JLBLine** [comment]
Right, with this commit 2f44420ce5c8987cf2f964d4b797d326c3459fb8, I believe I've made my `uvfits` files compatible with `pyuvdata`, in so far as I can make a `pyuvdata.UVData` object and read my `uvfits` files in with no errors.

**Comment by JLBLine** [comment]
@plaplant @mkolopanis I believe this has been addressed, please have a look. I'm not familiar with `pyuvdata` so beyond reading data in I'm not sure what tests to run

**Comment by plaplant** [comment]
I have not independently verified this, but it sounds like @mkolopanis has. That's proof enough for me 🙂

**Comment by JLBLine** [comment]
Thanks all, I'll close this now.
