### ISSUE TITLE
JOSS review issue 7 (Community Guidelines)

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/WODEN#20]
Add some community guidelines for how to contribute

https://github.com/openjournals/joss-reviews/issues/3676

**Comment by JLBLine** [comment]
With commit 39f2deab0268adfbeda28fb7166dbb1bab2d79b7 I've added the [CONTRIBUTION_GUIDE.md](https://github.com/JLBLine/WODEN/blob/joss_review/CONTRIBUTION_GUIDE.md) and linked to that in the `README.md`.
@mkolopanis @plaplant I think this addresses the issue

**Comment by mkolopanis** [comment]
Thanks for the contribution guide. This addresses this issue as far as I am concerned.

**Comment by plaplant** [comment]
Very nice documentation! Looks great to me.

**Comment by JLBLine** [comment]
Thanks all, I'll close this now.
