### ISSUE TITLE
JOSS review issue 9 (float vs double)

### ISSUE THREAD

**Issue by JLBLine** [JLBLine/WODEN#22]
Allow the user to choose between float and double precision. I'll do this by adding a switch that will assign float or double during compilation. This means the same code will always be used, just with different precision. I'll then get CMake to create two executables, `woden_float` and `woden_double`, that `run_woden.py` will be able to call depending on user arguments.

https://github.com/openjournals/joss-reviews/issues/3676

**Comment by JLBLine** [comment]
As of commit d745659cf36efe9ee6750fd075b5597b7ad0de00, the "double" or "float" choice is working in the code and unit testing, and has been written up into the JOSS paper. Still need to re-run all benchmarks, and need to update the Documentation in places.

**Comment by JLBLine** [comment]
@mkolopanis @plaplant as of commit 8b139527cbfbc934a2f92442a3b3778710c3ffff the documentation should be caught up to the float/double precision comparisons so I think this issue has been resolved now

**Comment by mkolopanis** [comment]
The documentation updates look good to me. Thanks for adding this feature.

**Comment by plaplant** [comment]
This is a very nice addition. Thanks for adding it!

**Comment by JLBLine** [comment]
Thanks all, I'll close this now.
