### ISSUE TITLE
Output error when running two WODEN instances in the same directory.

### ISSUE THREAD

**Issue by JaidenCook** [JLBLine/WODEN#31]
Error occurs when running two WODEN instances in the same directory. Both instances write to the same temporary output files `output_visi_band$ID.dat`. In one instance this led to a FileNotFoundError on line 586, and 1658 in `run_woden.py`. This resulted in the final outputs of one band not being written.

**Comment by JLBLine** [comment]
In the latest version of WODEN everything is held in memory so this is no longer an issue. Hoorary.
